#!/usr/bin/env bash
# ==============================================================================
# Dynamic Material You Theme Engine (Matugen + Hyprland + Waybar + Kitty + Rofi)
# ==============================================================================

WP="${1:-$HOME/.config/hypr/wallpaper.jpg}"

if [ ! -f "$WP" ]; then
    echo "Wallpaper not found: $WP"
    exit 1
fi

TARGET_IMG="$WP"

# If video, extract a single frame for color analysis
if [[ "$WP" =~ \.(mp4|mkv|webm)$ ]]; then
    mkdir -p /tmp/hypr_thumbs
    ffmpeg -y -i "$WP" -ss 00:00:01 -vframes 1 /tmp/hypr_thumbs/frame.jpg >/dev/null 2>&1
    TARGET_IMG="/tmp/hypr_thumbs/frame.jpg"
fi

# Run matugen to extract color scheme
MATUGEN_JSON=$(matugen image "$TARGET_IMG" --source-color-index 0 -j hex 2>/dev/null)

if [ -z "$MATUGEN_JSON" ]; then
    # Fallback to standard sleek dark blue colors if matugen fails
    PRIMARY="#7aa2f7"
    SECONDARY="#bb9af7"
    TERTIARY="#7dcfff"
    SURFACE="#1a1b26"
    ON_SURFACE="#c0caf5"
    BACKGROUND="#16161e"
else
    PRIMARY=$(echo "$MATUGEN_JSON" | jq -r '.colors.primary.dark.color // "#7aa2f7"')
    SECONDARY=$(echo "$MATUGEN_JSON" | jq -r '.colors.secondary.dark.color // "#bb9af7"')
    TERTIARY=$(echo "$MATUGEN_JSON" | jq -r '.colors.tertiary.dark.color // "#7dcfff"')
    SURFACE=$(echo "$MATUGEN_JSON" | jq -r '.colors.surface.dark.color // "#1a1b26"')
    ON_SURFACE=$(echo "$MATUGEN_JSON" | jq -r '.colors.on_surface.dark.color // "#c0caf5"')
    BACKGROUND=$(echo "$MATUGEN_JSON" | jq -r '.colors.background.dark.color // "#16161e"')
fi

# Hex without '#' for Hyprland rgb()
P_HEX="${PRIMARY#'#'}"
S_HEX="${SECONDARY#'#'}"
T_HEX="${TERTIARY#'#'}"

# 1. Update Waybar Colors (colors.css)
mkdir -p "$HOME/.config/waybar"
cat > "$HOME/.config/waybar/colors.css" << EOF
/* Auto-generated by Material You / Matugen Engine */
@define-color primary $PRIMARY;
@define-color secondary $SECONDARY;
@define-color tertiary $TERTIARY;
@define-color surface $SURFACE;
@define-color on_surface $ON_SURFACE;
@define-color background $BACKGROUND;
@define-color bar_bg rgba(20, 20, 30, 0.75);
@define-color pill_bg rgba(30, 30, 46, 0.65);
@define-color pill_border rgba(255, 255, 255, 0.12);
EOF

# 2. Update Hyprland Theme (current.conf)
mkdir -p "$HOME/.config/hypr/themes"
cat > "$HOME/.config/hypr/themes/current.conf" << EOF
# Auto-generated by Material You / Matugen Engine
\$primary = rgb($P_HEX)
\$secondary = rgb($S_HEX)
\$tertiary = rgb($T_HEX)

general {
    col.active_border = rgb($P_HEX) rgb($S_HEX) 45deg
    col.inactive_border = rgba(303046aa)
}
EOF

# 3. Update Rofi Colors (colors.rasi)
mkdir -p "$HOME/.config/rofi"
cat > "$HOME/.config/rofi/colors.rasi" << EOF
* {
    accent: $PRIMARY;
    bg: rgba(22, 22, 30, 0.90);
    fg: $ON_SURFACE;
    secondary: $SECONDARY;
    surface: $SURFACE;
}
EOF

# 4. Update Kitty Colors (colors.conf)
mkdir -p "$HOME/.config/kitty"
cat > "$HOME/.config/kitty/colors.conf" << EOF
# Auto-generated Material You Kitty Scheme
foreground $ON_SURFACE
background #12131a
selection_foreground #12131a
selection_background $PRIMARY
cursor $PRIMARY
active_border_color $PRIMARY
inactive_border_color #282a36
active_tab_foreground #12131a
active_tab_background $PRIMARY
inactive_tab_foreground $ON_SURFACE
inactive_tab_background #1a1b26
EOF

# 5. Reload apps smoothly
pkill -SIGUSR1 kitty 2>/dev/null || true
hyprctl reload >/dev/null 2>&1 || true
pkill -SIGUSR2 waybar 2>/dev/null || (pkill waybar; waybar >/dev/null 2>&1 &)

echo "Material You theme applied for $WP (Primary: $PRIMARY)"
