preload = /home/jannik/Pictures/wallpaper_jannik_1920.png
preload = /home/jannik/Pictures/wallpaper_jannik_2560.png
wallpaper = DP-2,/home/jannik/Pictures/wallpaper_jannik_1920.png
wallpaper = HDMI-A-1,/home/jannik/Pictures/wallpaper_jannik_1920.png
wallpaper = DP-1,/home/jannik/Pictures/wallpaper_jannik_2560.png
