# --- Kitty Legacy Dark ---
font_family      JetBrainsMono Nerd Font
font_size        11.0
background_opacity 0.85
background_blur 15
confirm_os_window_close 0
cursor_shape beam
shell zsh

# Tokyo Night Colors (Dunkel)
foreground            #a9b1d6
background            #1a1b26
selection_foreground  #ffffff
selection_background  #283457
cursor                #c0caf5
cursor_text_color     #1a1b26
